# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bef4db645862ed8b7499a10c99956eaf844bc12325e136375afd9ee3b1f3100aea8146cf58dbfe1da64fb596beca0588c6f4c83b19c61ecb034f0cb291bceb19

test:
  secret_key_base: 2d6f55b21a15dcdecb468f0006c3d1037087944e95c0e5d957f58e6c3e0a07f90a860efff3f03d22d9245b4f9248437aa06101ed8e7057490d0c5c5b4609650b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
